Fix CI build missing new LDAP package dependency
Fixes the following build error during the pip install st2/requirements.txt
```
    Modules/constants.h:7:10: fatal error: lber.h: No such file or directory
     #include "lber.h"
              ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
```